TOP := ../..

ROOT_PATH := $(TOP)/app

TARGET := libservice
TEMPLATE := static_lib

SOURCES	:= \
	service_init.c \
	service_manager.c \
	service_system.c \
	service_touch.c

include $(TOP)/Makefile.include
