#ifndef __PLATFORM_STM32_MEM_H__
#define __PLATFORM_STM32_MEM_H__

#define STM32_FLASH_SIZE 		 (__PLATFORM_FLASH_SIZE__ << 10)
#define STM32_FLASH_ADDR 		 (__PLATFORM_FLASH_ADDR__)
#define STM32_FLASH_SECTOR_SIZE	 (__PLATFORM_FLASH_BLOCK_SIZE__)
#define STM32_FLASH_SECTOR_COUNT (__PLATFORM_FLASH_BLOCK_COUNT__)
#define STM32_RAM_SIZE			 (__PLATFORM_RAM_SIZE__ << 10)
#define STM32_RAM_ADDR			 (__PLATFORM_RAM_ADDR__)

#define STM32_IMAGE_HEAD_SIZE	(0x200)

#define MEMLAYOUT_FLASH_MEM_ADDR (STM32_FLASH_ADDR)
#define MEMLAYOUT_FLASH_MEM_SIZE (STM32_FLASH_SIZE)
#define MEMLAYOUT_FLASH_MEM_END  (MEMLAYOUT_FLASH_MEM_ADDR + MEMLAYOUT_FLASH_MEM_SIZE)

#define MEMLAYOUT_IBOOT_MEM_ADDR (STM32_FLASH_ADDR)
#define MEMLAYOUT_IBOOT_MEM_SIZE (CONFIG_IBOOT_MAX_SIZE)
#define MEMLAYOUT_IBOOT_MEM_END  (MEMLAYOUT_IBOOT_MEM_ADDR + MEMLAYOUT_IBOOT_MEM_SIZE)

#define MEMLAYOUT_ROM_INFO_MEM_ADDR (MEMLAYOUT_IBOOT_MEM_END)
#define MEMLAYOUT_ROM_INFO_MEM_SIZE (2 << 10)
#define MEMLAYOUT_ROM_INFO_MEM_END  (MEMLAYOUT_ROM_INFO_MEM_ADDR + MEMLAYOUT_ROM_INFO_MEM_SIZE)

#define MEMLAYOUT_XBOOT_MEM_ADDR (MEMLAYOUT_ROM_INFO_MEM_END)
#define MEMLAYOUT_XBOOT_MEM_SIZE (CONFIG_XBOOT_MAX_SIZE)
#define MEMLAYOUT_XBOOT_MEM_END  (MEMLAYOUT_XBOOT_MEM_ADDR + MEMLAYOUT_XBOOT_MEM_SIZE)

#define MEMLAYOUT_UBOOT_MEM_ADDR (MEMLAYOUT_XBOOT_MEM_END)
#define MEMLAYOUT_UBOOT_MEM_SIZE (CONFIG_UBOOT_MAX_SIZE)
#define MEMLAYOUT_UBOOT_MEM_END  (MEMLAYOUT_UBOOT_MEM_ADDR + MEMLAYOUT_UBOOT_MEM_SIZE)

#define MEMLAYOUT_APP_MEM_ADDR 	 (MEMLAYOUT_UBOOT_MEM_END)
#define MEMLAYOUT_APP_MEM_SIZE 	 (CONFIG_APP_MAX_SIZE)
#define MEMLAYOUT_APP_MEM_END  	 (MEMLAYOUT_APP_MEM_ADDR + MEMLAYOUT_APP_MEM_SIZE)

#define MEMLAYOUT_FS_MEM_ADDR 	 (MEMLAYOUT_APP_MEM_END)
#define MEMLAYOUT_FS_MEM_SIZE  	 (MEMLAYOUT_FLASH_MEM_END - MEMLAYOUT_APP_MEM_END)
#define MEMLAYOUT_FS_MEM_END   	 (MEMLAYOUT_FLASH_MEM_END)

#endif
